services:
  - type: web
    name: create-studios-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: create-db
          property: connectionString

  - type: postgres
    name: create-db
    plan: free
