services:
  - type: web
    name: create-studios-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: wz3j*e_7q!07*^3jb&wj50v9n2)zo+7!!7cqz2k69lfrz2tj7j
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: create-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: EMAIL_HOST
        value: smtp.office365.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: info@createstudiosleicester.co.uk
      - key: EMAIL_HOST_PASSWORD
        value: your-outlook-app-password
      - key: DEFAULT_FROM_EMAIL
        value: info@createstudiosleicester.co.uk

  - type: postgres
    name: create-db
    plan: free
